# Generated by Django 4.2 on 2025-07-18 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='data_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 18, 13, 46, 2, 325809, tzinfo=datetime.timezone.utc)),
        ),
    ]
