# Generated by Django 4.2 on 2025-07-18 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_data_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='data_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
