# Generated by Django 4.2 on 2025-07-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_data_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='data_created',
            new_name='date_created',
        ),
    ]
